before_deploy: git config --global user.email publish@travis.github && git config --global user.name "Freshchris01"
language: node_js
node_js:
  - "10"
script:
  - npm run lint
  - npm run build
  - npm run test
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#   keep-history: true
#   on:
#     branch: master
#   script:
#   - npm run deploy